### ISSUE TITLE
Can't run which_direction demo

### ISSUE THREAD

**Issue by clebio** [jhamrick/pycon-2014-talk#1]
Good morning,

I've spent a few hours just now trying to get the `which_direction.py` demo working. I got Panda3d installed (v1.9.0, though I tried 1.9.1 both from package and from source). I'm running ubuntu 15.04 (Vivid Vervet).

What I keep running up against is an import error, `ImportError: dynamic module does not define init function (initlibpanda)`. Specifically:

``` bash
$ python which_direction.py 
Loading config '/home/caleb/dev/pycon-2014-talk/demos/Config.prc'
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "which_direction.py", line 229, in <module>
    DirectionExperiment.create(stimulus=stims, stimtype=stimtypes)
  File "/home/caleb/dev/pycon-2014-talk/demos/demo/viewer.py", line 34, in create
    app.init_ssos()
  File "/home/caleb/dev/pycon-2014-talk/demos/demo/viewer.py", line 123, in init_ssos
    ssos = load_ssos(self.options['stimulus'])
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/display/viewer.py", line 500, in load
    ssos.append(SSO.load_tree(filename))
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 417, in load_tree
    types, props, porder = pickle.load(fid)
ImportError: dynamic module does not define init function (initlibpanda)
```

While the stack trace indicates this is happening within the Scenism dependency, I suspect it has something to do with the way that the `cpo` files are pickled, since if I just try to unpickle one directly, I see the same:

``` python
python -c 'from pickle import Unpickler; Unpickler(open("./stimuli/round-wooden-floor.cpo", "r")).load()'                              
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: dynamic module does not define init function (initlibpanda)
```

I'm fairly sure the package was created on a Mac (based on the youtube video of your talk...), and I wonder whether this is a cross-platform issue related to the pickling. But I'm not sure what's contained in the pickles, so just sort of guessing right now.

I should mention that the `tutorial.py` demo runs fine.

I have a mac laptop for work, and on there figured I try this as well. Perversely, when I run both the unpickler code or even a simple Panda3d import on that laptop, I get an honest-to-goodness `segmentation fault`. So that's fun. I'd expected the mac to fare better, not worse. C'est la vie.

**Comment by jhamrick** [comment]
Sigh, sorry about that. I would totally believe this is a cross-platform issue with pickle. These were saved using v1.9.0 but a pre-release version of it that probably isn't quite the same as the released version of it. I'll have a look and see if I can maybe re-save them using the released version...

**Comment by clebio** [comment]
Hey, no worries. Thanks for looking into it. Honestly, the video of your talk gave me enough information to get started -- Blender models exported to `.egg` and loaded to Panda3D, bullet physics, etc. -- that I'm content working on my own apps at this point. But it would be fun to get the `which direction` program working, too.

Besides, whenever I say "which direction", it makes me think of a British boy band. That makes me laugh.

**Comment by jhamrick** [comment]
Ok, here's something to try. I just pushed a commit which added all the .cpo files as json files, as well as a script to convert them back to .cpo. From the `demos` folder, run:

```
python json_to_sso.py
```

This will overwrite all the `.cpo` files and should allow you to then run the demo. Let me know if that works!

**Comment by clebio** [comment]
Well, that initially gave me the same result. But after debugging it a bit, I made the following change:

``` bash
diff --git i/demos/json_to_sso.py w/demos/json_to_sso.py
index 327ce30..e055219 100644
--- i/demos/json_to_sso.py
+++ w/demos/json_to_sso.py
@@ -38,6 +38,8 @@ for filename in sso_paths:
     for p in props:
         for prop, val in p.items():
             if isinstance(val, dict) and "__class__" in val:
+                if val["__class__"][0] == 'libpanda':
+                    val["__class__"][0] = 'panda3d.core'
                 cls = import_class(val["__class__"][0], val["__class__"][1])
                 p[prop] = cls(*val["value"])
```

With that, the conversion script now runs. When I then run the `which_direction` demo, I get the following:

``` bash
$ python which_direction.py 
Loading config '/home/caleb/dev/pycon-2014-talk/demos/Config.prc'
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "which_direction.py", line 229, in <module>
    DirectionExperiment.create(stimulus=stims, stimtype=stimtypes)
  File "/home/caleb/dev/pycon-2014-talk/demos/demo/viewer.py", line 34, in create
    app.init_ssos()
  File "/home/caleb/dev/pycon-2014-talk/demos/demo/viewer.py", line 123, in init_ssos
    ssos = load_ssos(self.options['stimulus'])
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/display/viewer.py", line 500, in load
    ssos.append(SSO.load_tree(filename))
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 420, in load_tree
    top = cls.build_tree(ssos, porder)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 311, in build_tree
    nodes = [x if isinstance(x, NodePath) else cls(props=x) for x in X]
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 418, in <genexpr>
    ssos = (cls._load(type_, prop) for type_, prop in izip(types, props))
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/util/combomethod.py", line 37, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 378, in _load
    sso = type_(props=props, other=other)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/pso.py", line 342, in __init__
    SSO.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 42, in __init__
    self.apply_prop(props, other=other)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/sso.py", line 124, in apply_prop
    method(prop)
  File "/usr/local/lib/python2.7/dist-packages/scenesim-0.3-py2.7.egg/scenesim/objects/pso.py", line 444, in set_into_collide_mask
    into_collide_mask = BitMask32.bit(into_collide_mask)
OverflowError: value 4294967295 out of range for signed integer
```

So I definitely think this is something platform-specific across mac and linux. What are the CPO and JSON files? Are they exports from Blender or from some other source program?

At any rate, definitely not a big deal. I'm just curious about the demo, but could also just work on new models and such.

**Comment by clebio** [comment]
Sorry, had pasted the original stack trace -- edited my previous comment to update with the new one. Main bit being:

```
OverflowError: value 4294967295 out of range for signed integer
```
